version: "3"
services:
  database:
    image: "redis:7.0"
    restart: always
    # hostname: redis
    container_name: redis-database
    ports:
      - "6379:6379"
    environment:
      - REDIS_URL=redis://redis:6379
    command: redis-server --save 20 1 --loglevel warning