version: "3"
services:
  database:
    image: "redis:alpine"
    container_name: database
    ports:
      - "6379:6379"
  server:
    build: ./server
    container_name: node-server
    ports:
      - "3001:3001"
  client:
    build: ./client
    container_name: react-client
    ports:
      - "80:80"