version: "3"
services:
  database:
    image: "redis:latest"
    hostname: redis
    ports:
      - "6379:6379"
  server:
    build: .
    ports:
      - "3001:3001"
    environment:
      - PORT=3001